version: '3'

networks:
  recyclarr:
    name: recyclarr

volumes:
  radarr_nightly:
  radarr_latest:
  sonarr_nightly:
  sonarr_latest:

services:
  radarr_latest:
    image: ghcr.io/hotio/radarr
    networks:
      recyclarr:
        aliases:
          - radarr_latest
    ports:
      - 7878:7878
    volumes:
      - radarr_latest:/config
    environment:
      - TZ=America/Chicago

  radarr_nightly:
    image: ghcr.io/hotio/radarr:nightly
    networks:
      recyclarr:
        aliases:
          - radarr_nightly
    ports:
      - 7879:7878
    volumes:
      - radarr_nightly:/config
      - ./certs:/certs:ro
    environment:
      - TZ=America/Chicago

  sonarr_latest:
    image: ghcr.io/hotio/sonarr
    networks:
      recyclarr:
        aliases:
          - sonarr_latest
    ports:
      - 8989:8989
    volumes:
      - sonarr_latest:/config
    environment:
      - TZ=America/Chicago

  sonarr_nightly:
    image: ghcr.io/hotio/sonarr:nightly
    networks:
      recyclarr:
        aliases:
          - sonarr_nightly
    ports:
      - 8990:8989
    volumes:
      - sonarr_nightly:/config
    environment:
      - TZ=America/Chicago
