# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# An empty starter config to use with Recyclarr. Update the values below as needed for your
# instance. You will be required to update the `api_key` and `base_url` for each instance you want
# to use.
#
# If you'd rather use pre-built configuration instead of building your own from scratch, see these
# pages:
# - Config Templates: https://recyclarr.dev/wiki/guide-configs/
# - CLI Command: http://recyclarr.dev/wiki/cli/config/list/templates/
#
# This file WILL NOT WORK as it currently is. You need to read the documentation and build this
# configuration from scratch. Note that there's no "one size fits all" configuration. Please refer
# to the TRaSH Guides to understand how to build the appropriate configuration based on your
# hardware setup and capabilities.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/yaml/config-reference/
#
# Want a more flexible file layout?
# See: https://recyclarr.dev/wiki/file-structure/

# Configuration specific to Sonarr. For Radarr, the layout is the same.
# See: http://recyclarr.dev/wiki/yaml/config-reference/basic/
sonarr:
  series:
    # Set the URL/API Key to your actual instance
    base_url: http://localhost:8989
    api_key: YOUR_KEY_HERE

    # See: https://recyclarr.dev/wiki/yaml/config-reference/quality-definition/
    quality_definition:

    # See: http://localhost:3000/wiki/yaml/config-reference/quality-profiles/
    quality_profiles:

    # See: http://localhost:3000/wiki/yaml/config-reference/custom-formats/
    custom_formats:

    # See: http://localhost:3000/wiki/yaml/config-reference/media-naming/
    media_naming:
